name: Captcha Solver

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  solve-captcha:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgbm-dev libnss3 libatk-bridge2.0-0 libgtk-3-0 libgdk-pixbuf2.0-0
        
    - name: Install Node dependencies
      run: |
        npm install puppeteer puppeteer-extra puppeteer-extra-plugin-stealth axios --verbose
        
    - name: Run captcha solver
      run: node captcha-solver.js
      
    - name: Upload screenshot
      uses: actions/upload-artifact@v4
      with:
        name: captcha-screenshot
        path: screenshot.png
        if-no-files-found: warn
