name: Run CAPTCHA Solver

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run-captcha-solver:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # or the version you need

    - name: Install dependencies
      run: npm install puppeteer puppeteer-extra puppeteer-extra-plugin-stealth axios

    - name: Run CAPTCHA Solver
      run: node captcha-solver.js

    - name: Upload screenshot
      uses: actions/upload-artifact@v2
      with:
        name: screenshot
        path: screenshot.png
