name: Run CAPTCHA Solver

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run-captcha-solver:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'  # Use the latest recommended version

    - name: Install dependencies
      run: npm install puppeteer puppeteer-extra puppeteer-extra-plugin-stealth axios

    - name: Run CAPTCHA Solver
      run: node captcha-solver.js

    - name: Upload screenshot
      if: always()  # Ensure this step runs even if the previous step fails
      uses: actions/upload-artifact@v3
      with:
        name: screenshot
        path: screenshot.png
